# Generated by Django 5.0.7 on 2026-05-04 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=280)),
                ('summary', models.TextField(blank=True)),
                ('external_url', models.URLField(blank=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('starts_at', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Events',
                'ordering': ['sort_order', '-starts_at', '-id'],
            },
        ),
    ]
