# Generated by Django 5.0.7 on 2026-03-09 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('frontend', 'Frontend Developer'), ('backend', 'Backend Developer'), ('fullstack', 'Full Stack Developer'), ('mobile', 'Mobile Developer'), ('devops', 'DevOps Engineer'), ('designer', 'UI/UX Designer')], max_length=20)),
                ('question_text', models.TextField()),
                ('options', models.JSONField()),
                ('correct_answer', models.IntegerField(default=0)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['role', 'difficulty', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SkillTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('frontend', 'Frontend Developer'), ('backend', 'Backend Developer'), ('fullstack', 'Full Stack Developer'), ('mobile', 'Mobile Developer'), ('devops', 'DevOps Engineer'), ('designer', 'UI/UX Designer')], max_length=20)),
                ('questions', models.JSONField()),
                ('answers', models.JSONField()),
                ('result_level', models.CharField(choices=[('beginner', 'Beginner'), ('junior', 'Junior'), ('middle', 'Middle'), ('senior', 'Senior')], max_length=20)),
                ('feedback', models.TextField()),
                ('score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
