# Generated by Django 5.0.7 on 2026-03-13 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['difficulty', 'created_at']},
        ),
        migrations.AddField(
            model_name='skilltest',
            name='score_percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10),
        ),
    ]
