# Generated by Django 5.0.7 on 2026-03-29 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0003_alter_question_options_skilltest_score_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skilltest',
            name='role',
            field=models.CharField(choices=[('frontend', 'Frontend Developer'), ('backend', 'Backend Developer'), ('fullstack', 'Full Stack Developer'), ('mobile', 'Mobile Developer'), ('devops', 'DevOps Engineer'), ('designer', 'UI/UX Designer'), ('react', 'React Developer'), ('vue', 'Vue Developer'), ('python', 'Python Developer'), ('java', 'Java Developer'), ('javascript', 'JavaScript Developer'), ('sql', 'SQL Developer'), ('mongodb', 'MongoDB Developer'), ('docker', 'Docker Developer'), ('aws', 'AWS Developer'), ('testing', 'Testing Engineer')], max_length=20),
        ),
    ]
