# Generated by Django 5.0.7 on 2026-03-29 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='generated_cv',
            field=models.TextField(blank=True, help_text='AI-generated professional CV content'),
        ),
    ]
