# Generated by Django 5.0.7 on 2026-03-09 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('requirements', models.TextField()),
                ('role', models.CharField(choices=[('frontend', 'Frontend Developer'), ('backend', 'Backend Developer'), ('fullstack', 'Full Stack Developer'), ('mobile', 'Mobile Developer'), ('devops', 'DevOps Engineer'), ('designer', 'UI/UX Designer')], max_length=20)),
                ('experience_level', models.CharField(choices=[('beginner', 'Beginner'), ('junior', 'Junior'), ('middle', 'Middle'), ('senior', 'Senior')], max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('salary_min', models.IntegerField(blank=True, null=True)),
                ('salary_max', models.IntegerField(blank=True, null=True)),
                ('remote', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.IntegerField(help_text='Match percentage from 0-100')),
                ('skill_level', models.CharField(choices=[('beginner', 'Beginner'), ('junior', 'Junior'), ('middle', 'Middle'), ('senior', 'Senior')], max_length=20)),
                ('is_recommended', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='jobs.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_matches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-match_score', '-created_at'],
                'unique_together': {('user', 'job')},
            },
        ),
    ]
